### ISSUE TITLE
Two Phase example error - acum_sum not defined

### ISSUE THREAD

**Issue by kingaj12** [JaimeLeal/projects#1]
# PLOT and make a gif with ffmpeg

#Transform results to psi

p_oil = results['p_oil'][:,:]/ u.psi

sw = results['sw'][:,:]

​

for k in np.arange(0, acum_sum.size, 1):

    plotCellValues2D(grid, p_oil[:, k], 'inferno', np.min(p_oil), np.max(p_oil),

                     title='Oil pressure. {:.3f} days'.format(acum_sum[k]), 

                     filename='{}\\2ph_ex1_po_{}'.format(imgpath,k))

​

for k in np.arange(0, acum_sum.size, 1):

    plotCellValues2D(grid, sw[:, k], 'plasma', np.min(sw), np.max(sw),

                     title='Water saturation. {:.3f} days'.format(acum_sum[k]), 

                     filename='{}\\2ph_ex1_sw_{}'.format(imgpath,k))

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-3-dbdec290e196> in <module>()
      4 sw = results['sw'][:,:]
      5 
----> 6 for k in np.arange(0, acum_sum.size, 1):
      7     plotCellValues2D(grid, p_oil[:, k], 'inferno', np.min(p_oil), np.max(p_oil),
      8                      title='Oil pressure. {:.3f} days'.format(acum_sum[k]),

NameError: name 'acum_sum' is not defined

**Comment by kingaj12** [comment]
I should also say:  thanks for providing this nice code!

**Comment by kingaj12** [comment]
I think it should be 

`acum_sum = np.cumsum(sch.timesteps) / u.day`

**Comment by JaimeLeal** [comment]
You are right. I added the missing definition to the notebook, it should work correctly now. Thanks.
